#!/bin/bash

## Author : Aditya Shakya
## Email  : adi1090x@gmail.com

#colors
R='\033[1;31m'
B='\033[1;34m'
C='\033[0;36m'
G='\033[1;32m'
W='\033[1;37m'
Y='\033[1;33m'

DIR="$(pwd)"

echo
echo -e $B"   ┌───────────────────────────────────────────┐"
echo -e $B"   │ $R  ╺┳╸┏━╸┏━┓┏┳┓╻╺┳╸┏━╸  $G ┏━┓╺┳╸╻ ╻╻  ┏━╸  $B │"
echo -e $B"   │ $R   ┃ ┣╸ ┣┳┛┃┃┃┃ ┃ ┣╸   $G ┗━┓ ┃ ┗┳┛┃  ┣╸   $B │"
echo -e $B"   │ $R   ╹ ┗━╸╹┗╸╹ ╹╹ ╹ ┗━╸  $G ┗━┛ ╹  ╹ ┗━╸┗━╸  $B │"
echo -e $B"   └───────────────────────────────────────────┘"
echo -e $B"   [$R*$B] By-$Y Aditya Shakya $R//$Y adi1090x"
echo

if [ ! -L /usr/bin/termite-style ] && [ ! -d /usr/share/termite-style ]; then
echo -e $G"   [*] termite-style is not installed."
echo
exit
fi

echo -e $G"   [*] uninstalling termite-style..."
echo

echo -e $Y"   [*] Need 'sudo' to remove files from '/usr' dir."
echo
sudo rm -rf /usr/share/termite-style/
sudo rm -rf /usr/share/fonts/tsf/
sudo fc-cache

if [ -L /usr/bin/termite-style ]; then
	sudo rm /usr/bin/termite-style
fi

if [ ! -L /usr/bin/termite-style ] && [ ! -d /usr/share/termite-style ]; then
echo -e $G"   [*] Uninstalled Successfully."
echo
else
echo -e $R"   [!] Error Occured."
echo
fi
